- hosts: all
  become: true
  tasks:
    - name: Atualiza o cache do apt
      apt:
        update_cache: yes

    - name: Instala o Docker
      apt:
        name: docker.io
        state: present

    - name: Inicia e habilita o Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Cria o diretório para dados persistentes do MongoDB
      file:
        path: /data/mongo
        state: directory
        owner: 1000 # UID padrão para o usuário no Docker Mongo
        group: 1000
        mode: "0755"

    - name: Executa o contêiner MongoDB
      docker_container:
        name: mongodb
        image: mongo:latest
        state: started
        restart_policy: always
        ports:
          - "27017:27017"
        volumes:
          - /data/mongo:/data/db
        env:
          MONGO_INITDB_ROOT_USERNAME: "admin"
          MONGO_INITDB_ROOT_PASSWORD: "password"
      register: mongodb_container

    - name: Adiciona o usuário ao grupo Docker para acesso sem sudo
      user:
        name: vagrant
        groups: docker
        append: yes

- import_playbook: playbook-node-config.yml
