---
- import_playbook: playbook-docker.yml

- hosts: all
  become: true
  tasks:
    - name: Pull PostgreSQL Docker image
      docker_image:
        name: postgres
        tag: "latest"
        source: pull

    - name: Cria o diretório para dados persistentes do Postgres
      file:
        path: /data/postgres
        state: directory
        owner: 100
        group: 1000
        mode: "0755"

    - name: Run PostgreSQL container
      docker_container:
        name: postgres_container
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tcc
        ports:
          - "5432:5432"
        volumes:
          - /var/lib/docker_volumes/postgres_data:/var/lib/postgresql/dat
        state: started
        restart_policy: always

    - name: Wait for PostgreSQL to be ready
      wait_for:
        host: "localhost"
        port: 5432
        state: started
        timeout: 60

- import_playbook: playbook-node-config.yml
