---
- hosts: all
  become: true
  tasks:
    - name: Add NodeSource repository for Node.js 16.x
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js 16.x repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x bionic main
        state: present

    - name: Update apt cache after adding Node.js repo
      apt:
        update_cache: yes

    - name: Install Node.js (16.x version)
      apt:
        name: nodejs
        state: present

    - name: Criar pasta para scripts
      file:
        path: /home/vagrant/scripts
        state: directory
        owner: vagrant
        mode: "0755"

    - name: Copy scripts to VM (excluding node_modules)
      copy:
        src: ../automation-scripts/
        dest: /home/vagrant/scripts
        owner: vagrant
        mode: "0755"

    - name: Remove .env file on target VM
      file:
        path: /home/vagrant/scripts/.env
        state: absent

    - name: Install dependencies
      npm:
        path: /home/vagrant/scripts
        state: present
    - name: Create .env file for database configuration
      copy:
        dest: /home/vagrant/scripts/.env
        content: |
          DB_USER=admin
          DB_HOST=localhost
          DB_NAME=tcc
          DB_PASSWORD=postgres
          DB_PORT=5432
          MONGO_URL=mongodb://admin:password@localhost:27017
        owner: vagrant
        mode: "0600"
