---
- import_playbook: playbook-docker.yml

- hosts: all
  become: true
  tasks:
    - name: Baixa a imagem Docker do MongoDB
      docker_image:
        name: mongo
        tag: "latest"
        source: pull

    - name: Cria o diretório para dados persistentes do MongoDB
      file:
        path: /data/mongo
        state: directory
        owner: 100
        group: 1000
        mode: "0755"

    - name: Executa o contêiner MongoDB
      docker_container:
        name: mongodb
        image: mongo:latest
        state: started
        restart_policy: always
        ports:
          - "27017:27017"
        volumes:
          - /data/mongo:/data/db
        env:
          MONGO_INITDB_ROOT_USERNAME: "admin"
          MONGO_INITDB_ROOT_PASSWORD: "password"
      register: mongodb_container

    - name: Aguarda o MongoDB estar pronto
      wait_for:
        host: "localhost"
        port: 27017
        state: started
        timeout: 60

- import_playbook: playbook-node-config.yml
